### ISSUE TITLE
Create user model

### ISSUE THREAD

**Issue by jeremystephencobb** [andrewmcgov/express-cms#11]
- [x] pick a sign in flow (I like using Google personally)

- [x] create the schema

- [x] join to Post model

- [x] determine a convention for our URL structure.

- [x] how to edit posts

I was thinking we could mimic all the URLs and append `/admin` to them, so if you want to see all the posts it would be `/posts` on the front end and `/admin/posts` in admin?

Just an idea

**Comment by andrewmcgov** [comment]
Resolved in recent PRs!
